### ISSUE TITLE
Can I please join the organisation?

### ISSUE THREAD

**Issue by NS007-dev** [Alphasians/hacktoberfest-practice#2]
@Sonichigo is it possible for me to join the organisation please? I would like to help out more. Thanks.

**Comment by Sonichigo** [comment]
Yeah, OFC!!
https://github.com/Alphasians/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

and then join our discord

**Comment by NS007-dev** [comment]
Thank you.
